import React from "react";
import Image from "next/image";
import type { Metadata } from "next";

import "@/app/globals.css";
import "@/styles/pages/experience.css";

import suitcaseIcon from "@/public/images/icons/suitcase-icon.svg";
import terminalIcon from "@/public/images/icons/terminal-icon.svg";
import cognitionIcon from "@/public/images/icons/cognition-icon.svg";
import schoolIcon from "@/public/images/icons/school-icon.svg";

export const metadata: Metadata = {
  title: "Experience & Skills | Alejandro Suarez DEV",
  description:
    "Explore the professional journey, technical expertise, and education of Alejandro Suarez, Full-Stack Developer and Project Lead.",
};

export default function Experience() {
  return (
    <>
      <header>
        <h1>
          Experience &amp; <span>Expertise</span>
        </h1>
        <p>
          Building scalable digital solutions, leading web project workflows,
          and delivering high-performance applications.
        </p>
      </header>

      <main>
        <div className="professional-journey">
          <h2>
            <Image
              src={suitcaseIcon}
              alt="Suitcase Icon"
              width={24}
              height={24}
            />
            Professional Journey
          </h2>

          <div className="experience">
            <div className="experience-item">
              <div className="time-line">
                <div className="circle current"></div>
                <div className="line current"></div>
              </div>
              <div className="experience-data">
                <p className="dates">February 2025 &ndash; June 2025</p>
                <h3 className="job-position">
                  Front-End Developer &amp; Project Lead
                </h3>
                <h4 className="company">Meliora AI &bull; Remote</h4>
                <p className="job-description">
                  Developed a full-featured accounting web application using
                  React and Tailwind CSS, handling UI design, interface logic,
                  and validations while creating intuitive, user-centered
                  interfaces optimized for both desktop and mobile devices. Led
                  the project using the Scrum framework, managing tasks through
                  GitHub, maintaining clear client communication, and tracking
                  progress to ensure all project objectives were met with a 100%
                  on-time delivery rate.
                </p>
              </div>
            </div>

            <div className="experience-item">
              <div className="time-line">
                <div className="circle"></div>
                <div className="line"></div>
              </div>
              <div className="experience-data">
                <p className="dates">December 2024 &ndash; February 2025</p>
                <h3 className="job-position">AI Model Trainer</h3>
                <h4 className="company">Outlier AI &bull; Remote</h4>
                <p className="job-description">
                  Wrote prompts and evaluated responses generated by various
                  language models, assessing the quality, relevance, and
                  coherence of their outputs. Analyzed recurring error patterns
                  and proposed adjustments to improve model performance, while
                  documenting findings and insights to support improvements in
                  accuracy, clarity, and overall response quality.
                </p>
              </div>
            </div>

            <div className="experience-item">
              <div className="time-line">
                <div className="circle"></div>
                <div className="line"></div>
              </div>
              <div className="experience-data">
                <p className="dates">August 2022 &ndash; June 2023</p>
                <h3 className="job-position">Noob Games: Student Group</h3>
                <h4 className="company">
                  Tecnol&oacute;gico de Monterrey - Mexico
                </h4>
                <p className="job-description">
                  Founded and led the student group Noob Games, an initiative
                  aimed at helping students develop and apply skills in video
                  game development across multiple disciplines. Organized and
                  delivered training courses focused on core game development
                  concepts, fostering collaboration and hands-on learning among
                  participants.
                </p>
              </div>
            </div>
          </div>
        </div>

        <div className="skills-education">
          <div className="technical-skills">
            <h2 className="skills-headline">
              <Image
                src={terminalIcon}
                alt="Terminal Icon"
                width={24}
                height={24}
              />
              Technical Skills
            </h2>

            <div className="tech-skill-item">
              <div className="tech-skill-data">
                <p>Frontend (React/TailwindCSS)</p>
                <p className="percentage">85%</p>
              </div>
              <div className="progress-bar">
                <div className="progress" style={{ width: "85%" }}></div>
              </div>
            </div>

            <div className="tech-skill-item">
              <div className="tech-skill-data">
                <p>Backend (Node)</p>
                <p className="percentage">65%</p>
              </div>
              <div className="progress-bar">
                <div className="progress" style={{ width: "65%" }}></div>
              </div>
            </div>

            <div className="tech-skill-item">
              <div className="tech-skill-data">
                <p>Database (PostgreSQL)</p>
                <p className="percentage">75%</p>
              </div>
              <div className="progress-bar">
                <div className="progress" style={{ width: "75%" }}></div>
              </div>
            </div>

            <div className="tech-skill-item">
              <div className="tech-skill-data">
                <p>Version Control (Git/GitHub)</p>
                <p className="percentage">90%</p>
              </div>
              <div className="progress-bar">
                <div className="progress" style={{ width: "90%" }}></div>
              </div>
            </div>
          </div>

          <div className="soft-skills">
            <h2 className="skills-headline">
              <Image
                src={cognitionIcon}
                alt="Cognition Icon"
                width={24}
                height={24}
              />
              Soft Skills
            </h2>
            <ul className="skills-list">
              <li>Planning</li>
              <li>Agile</li>
              <li>Adaptability</li>
              <li>Leadership</li>
              <li>Communication</li>
              <li>Prioritization</li>
            </ul>
          </div>

          <div className="education">
            <h2 className="skills-headline">
              <Image
                src={schoolIcon}
                alt="School Icon"
                width={24}
                height={24}
              />
              Education
            </h2>

            <div className="education-item">
              <h3 className="degree">Diploma in Web Development</h3>
              <h4 className="institution">CICC (Canada)</h4>
              <p className="generation">Current</p>
            </div>

            <div className="education-item">
              <h3 className="degree">BS Computer Science</h3>
              <h4 className="institution">
                Tecnol&oacute;gico de Monterrey (Mexico)
              </h4>
              <p className="generation">Class of 2025</p>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}