export const experienceData = [
  {
    dates: "February 2025 – June 2025",
    jobPosition: "Front-End Developer & Project Lead",
    company: "Meliora AI • Remote",
    jobDescription:
      "Developed a full-featured accounting web application using React and Tailwind CSS, handling UI design, interface logic, and validations while creating intuitive, user-centered interfaces optimized for both desktop and mobile devices. Led the project using the Scrum framework, managing tasks through GitHub, maintaining clear client communication, and tracking progress to ensure all project objectives were met with a 100% on-time delivery rate.",
  },
  {
    dates: "December 2024 – February 2025",
    jobPosition: "AI Model Trainer",
    company: "Outlier AI • Remote",
    jobDescription:
      "Wrote prompts and evaluated responses generated by various language models, assessing the quality, relevance, and coherence of their outputs. Analyzed recurring error patterns and proposed adjustments to improve model performance, while documenting findings and insights to support improvements in accuracy, clarity, and overall response quality.",
  },
  {
    dates: "August 2022 – June 2023",
    jobPosition: "Noob Games: Student Group",
    company: "Tecnológico de Monterrey - Mexico",
    jobDescription:
      "Founded and led the student group Noob Games, an initiative aimed at helping students develop and apply skills in video game development across multiple disciplines. Organized and delivered training courses focused on core game development concepts, fostering collaboration and hands-on learning among participants.",
  },
];

export const skillsData = [
  {
    name: "Frontend (React/TailwindCSS)",
    percentage: 85,
  },
  {
    name: "Backend (Node)",
    percentage: 65,
  },
  {
    name: "Database (PostgreSQL)",
    percentage: 75,
  },
  {
    name: "Version Control (Git/GitHub)",
    percentage: 90,
  },
];

export const softSkills = [
  "Planning",
  "Agile",
  "Adaptability",
  "Leadership",
  "Communication",
  "Prioritization",
];

export const educationData = [
  {
    degree: "Diploma in Web Development",
    institution: "CICCC (Canada)",
    generation: "Current",
  },
  {
    degree: "BS Computer Science",
    institution: "Tecnológico de Monterrey (Mexico)",
    generation: "Class of 2025",
  },
];
